# Generated by Django 3.1.6 on 2021-10-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('date_of_joining', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=50)),
                ('reporting_manager', models.TextField()),
                ('emp_image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('password', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
