# Generated by Django 3.1.6 on 2021-10-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20211015_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_image',
            field=models.ImageField(blank=True, default='', upload_to='app1/static/images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
