# Generated by Django 3.1.6 on 2021-10-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20211015_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_image',
            field=models.ImageField(blank=True, default='', upload_to='static/app1/images'),
        ),
    ]
