# Generated by Django 3.1.6 on 2021-10-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20211015_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reporting_manager',
            field=models.CharField(max_length=50),
        ),
    ]
